"""Add legacy column

Revision ID: 19cf821edad6
Revises: f4b5614342fe
Create Date: 2024-05-15 16:12:34.910164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19cf821edad6'
down_revision: Union[str, None] = 'f4b5614342fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('headline', sa.Column('legacy', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('headline', 'legacy')
    # ### end Alembic commands ###
