"""Add description column

Revision ID: 1abfd92c13da
Revises: 6e4cd0cc82b3
Create Date: 2024-05-11 10:55:04.159727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1abfd92c13da'
down_revision: Union[str, None] = '6e4cd0cc82b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('named_entity', sa.Column('description', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('named_entity', 'description')
    # ### end Alembic commands ###
