"""Initial revision

Revision ID: 3803fccdb858
Revises: 
Create Date: 2024-02-10 11:34:22.008696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3803fccdb858'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('url', sa.String(length=100), nullable=False),
    sa.Column('_bias', sa.Integer(), nullable=False),
    sa.Column('_credibility', sa.Integer(), nullable=False),
    sa.Column('headline_only', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_accessed', sa.DateTime(), nullable=False),
    sa.Column('last_accessed', sa.DateTime(), nullable=False),
    sa.Column('agency_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=254), nullable=True),
    sa.Column('url', sa.String(length=254), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('failure', sa.Boolean(), nullable=False),
    sa.Column('artneg', sa.Float(), nullable=True),
    sa.Column('artneu', sa.Float(), nullable=True),
    sa.Column('artpos', sa.Float(), nullable=True),
    sa.Column('artcompound', sa.Float(), nullable=True),
    sa.Column('headneg', sa.Float(), nullable=True),
    sa.Column('headneu', sa.Float(), nullable=True),
    sa.Column('headpos', sa.Float(), nullable=True),
    sa.Column('headcompound', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agency.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article')
    op.drop_table('agency')
    # ### end Alembic commands ###
