"""Completed

Revision ID: 4216514cc3d8
Revises: b8495ae2aa86
Create Date: 2024-02-13 10:50:21.866598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4216514cc3d8'
down_revision: Union[str, None] = 'b8495ae2aa86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agency', 'headline_only')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agency', sa.Column('headline_only', sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###
