"""Add access time to headline

Revision ID: 49d362b5456c
Revises: 4216514cc3d8
Create Date: 2024-02-13 11:13:35.069035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49d362b5456c'
down_revision: Union[str, None] = '4216514cc3d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('headline', sa.Column('first_accessed', sa.DateTime(), nullable=False))
    op.add_column('headline', sa.Column('last_accessed', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('headline', 'last_accessed')
    op.drop_column('headline', 'first_accessed')
    # ### end Alembic commands ###
