"""Add Named Entities

Revision ID: 6dc7772c3a1c
Revises: f4b5614342fe
Create Date: 2024-05-10 15:52:17.149329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dc7772c3a1c'
down_revision: Union[str, None] = 'f4b5614342fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('named_entity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical', sa.String(length=255), nullable=False),
    sa.Column('patterns', sa.Text(), nullable=False),
    sa.Column('wikidata_id', sa.String(length=255), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('first_accessed', sa.DateTime(), nullable=False),
    sa.Column('last_accessed', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_named_entity_patterns'), 'named_entity', ['patterns'], unique=False)
    op.create_table('article_named_entity',
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('named_entity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['named_entity_id'], ['named_entity.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_named_entity')
    op.drop_index(op.f('ix_named_entity_patterns'), table_name='named_entity')
    op.drop_table('named_entity')
    # ### end Alembic commands ###
