"""Add legacy column

Revision ID: 6e4cd0cc82b3
Revises: 6dc7772c3a1c
Create Date: 2024-05-11 09:29:22.293484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e4cd0cc82b3'
down_revision: Union[str, None] = '6dc7772c3a1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('headline', sa.Column('legacy', sa.Boolean(), nullable=True))
    op.add_column('named_entity', sa.Column('type', sa.String(length=255), nullable=False))
    op.add_column('named_entity', sa.Column('label', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('named_entity', 'label')
    op.drop_column('named_entity', 'type')
    op.drop_column('headline', 'legacy')
    # ### end Alembic commands ###
