"""Add named entity code

Revision ID: aaaa95c41ca1
Revises: f4b5614342fe
Create Date: 2024-05-12 09:46:21.280583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaaa95c41ca1'
down_revision: Union[str, None] = 'f4b5614342fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('named_entity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=10), nullable=False),
    sa.Column('patterns', sa.Text(), nullable=False),
    sa.Column('wikidata_id', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('first_accessed', sa.DateTime(), nullable=False),
    sa.Column('last_accessed', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_named_entity_patterns'), 'named_entity', ['patterns'], unique=False)
    op.create_table('article_named_entity',
    sa.Column('headline_id', sa.Integer(), nullable=True),
    sa.Column('named_entity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['headline_id'], ['headline.id'], ),
    sa.ForeignKeyConstraint(['named_entity_id'], ['named_entity.id'], )
    )
    op.add_column('headline', sa.Column('legacy', sa.Boolean(), nullable=True))
    op.add_column('headline', sa.Column('ner_processed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('headline', 'ner_processed')
    op.drop_column('headline', 'legacy')
    op.drop_table('article_named_entity')
    op.drop_index(op.f('ix_named_entity_patterns'), table_name='named_entity')
    op.drop_table('named_entity')
    # ### end Alembic commands ###
