"""Add headline score to article

Revision ID: b76fcafdbd07
Revises: 11c586a63e76
Create Date: 2024-04-02 18:11:29.064655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b76fcafdbd07'
down_revision: Union[str, None] = '11c586a63e76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('topic_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'topic_score')
    # ### end Alembic commands ###
