"""Remove failure column

Revision ID: b8495ae2aa86
Revises: c31b19d947db
Create Date: 2024-02-13 10:16:45.727824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8495ae2aa86'
down_revision: Union[str, None] = 'c31b19d947db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'failure')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('failure', sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###
