"""Add assoc data

Revision ID: ce976f848d38
Revises: aaaa95c41ca1
Create Date: 2024-05-13 15:06:41.285446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce976f848d38'
down_revision: Union[str, None] = 'aaaa95c41ca1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('named_entity_association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('headline_id', sa.Integer(), nullable=False),
    sa.Column('named_entity_id', sa.Integer(), nullable=False),
    sa.Column('entity', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['headline_id'], ['headline.id'], ),
    sa.ForeignKeyConstraint(['named_entity_id'], ['named_entity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('article_named_entity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_named_entity',
    sa.Column('headline_id', sa.INTEGER(), nullable=True),
    sa.Column('named_entity_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['headline_id'], ['headline.id'], ),
    sa.ForeignKeyConstraint(['named_entity_id'], ['named_entity.id'], )
    )
    op.drop_table('named_entity_association')
    # ### end Alembic commands ###
