"""Add afinn

Revision ID: dc1d9812e857
Revises: e3eef3e22106
Create Date: 2024-02-21 16:57:02.263778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from afinn import Afinn


# revision identifiers, used by Alembic.
revision: str = 'dc1d9812e857'
down_revision: Union[str, None] = 'e3eef3e22106'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('headline', sa.Column('afinn', sa.Float(), nullable=True))
    # ### end Alembic commands ###
    afinn = Afinn()
    conn = op.get_bind()
    result = conn.execute(sa.text('SELECT id, title FROM headline;'))
    for headline in result.fetchall():
        conn.execute(sa.text(f'UPDATE headline SET afinn = {afinn.score(headline.title)} WHERE id = {headline.id}'))
    result.close()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('headline', 'afinn')
    # ### end Alembic commands ###
