"""Add country code column

Revision ID: e1ddf3a0373a
Revises: 3803fccdb858
Create Date: 2024-02-10 11:36:03.342558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1ddf3a0373a'
down_revision: Union[str, None] = '3803fccdb858'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agency', sa.Column('_country', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agency', '_country')
    # ### end Alembic commands ###
