"""Remove type column

Revision ID: eaf18b8a3602
Revises: 1abfd92c13da
Create Date: 2024-05-11 12:48:40.618259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaf18b8a3602'
down_revision: Union[str, None] = '1abfd92c13da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('named_entity', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('named_entity', sa.Column('type', sa.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###
