"""Add indices

Revision ID: f4b5614342fe
Revises: 00b0dddb59f6
Create Date: 2024-05-10 15:40:29.633573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4b5614342fe'
down_revision: Union[str, None] = '00b0dddb59f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_agency_name'), 'agency', ['name'], unique=False)
    op.create_index(op.f('ix_article_url'), 'article', ['url'], unique=False)
    op.create_index(op.f('ix_headline_processed'), 'headline', ['processed'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_headline_processed'), table_name='headline')
    op.drop_index(op.f('ix_article_url'), table_name='article')
    op.drop_index(op.f('ix_agency_name'), table_name='agency')
    # ### end Alembic commands ###
