name: Deploy

on:
  push:
    branches:
      - main  # or the branch of your choice

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy repository to Digital Ocean server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          SERVER_IP: ${{ secrets.IP_ADDRESS }}
          SERVER_USER: ${{ secrets.USERNAME }}
          SERVER_DIRECTORY: ${{ secrets.DIRECTORY }}
          EMAIL_CREDS: ${{ secrets.EMAIL_CRED_FILE }}
        run: |
          echo "Making ssh directory"
          mkdir -p ~/.ssh
          echo "Writing ssh key"
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          echo "Setting permissions"
          chmod 600 ~/.ssh/id_rsa
          echo "Adding server to known hosts"
          ssh-keyscan -H "$SERVER_IP" >> ~/.ssh/known_hosts
          echo "Copying repository to server"
          ssh -i ~/.ssh/id_rsa "$SERVER_USER"@"$SERVER_IP" "git -C $SERVER_DIRECTORY pull origin main "
          echo "Installing requirements"
          ssh -i ~/.ssh/id_rsa "$SERVER_USER"@"$SERVER_IP" "$SERVER_DIRECTORY/venv/bin/pip install -r $SERVER_DIRECTORY/requirements.txt"
          echo "Writing creds"
          echo "$EMAIL_CREDS" > .creds
          scp -i ~/.ssh/id_rsa .creds "$SERVER_USER"@"$SERVER_IP":/home/maudlin/maudlin2/
          echo "Running Migrations"
          ssh -i ~/.ssh/id_rsa "$SERVER_USER"@"$SERVER_IP" "cd $SERVER_DIRECTORY && ./venv/bin/alembic upgrade head"
          echo "Running Queue"
          ssh -i ~/.ssh/id_rsa "$SERVER_USER"@"$SERVER_IP" "nohup SERVER_LOCATION=/var/www/html /home/maudlin/maudlin2/venv/bin/python /home/maudlin/maudlin2/main.py > "$(date +%Y-%m-%d_%H-%M-%S)-log.txt" 2>&1 &"
          
